- name: Create a directory for configs | Deploy container | NginX-Podman
  file:
    path: "{{ nup_containers_data_dir }}/{{ nup_container_name }}/vhosts"
    recurse: true
    state: directory

- name: Render configs | Deploy container | NginX-Podman
  template:
    src: "{{ item }}"
    dest: "{{ nup_containers_data_dir }}/{{ nup_container_name }}/vhosts/{{ item | basename | regex_replace('\\.j2$', '') }}"
  register: nup_config
  with_fileglob:
    - ../templates/vhosts/*.j2

- name: Copy nginx config | Deploy container | NginX-Podman
  copy:
    src: nginx.conf
    dest: "{{ nup_containers_data_dir }}/{{ nup_container_name }}/nginx.conf"
  register: nup_ng_config

- name: Run container | Deploy container | NginX-Podman
  podman_container:
    name: "{{ nup_container_name }}"
    image: "{{ nup_container_name }}"
    state: started
    ports:
      - 80:80
    volumes:
      - "{{ nup_containers_data_dir }}/{{ nup_container_name }}/nginx.conf:/etc/nginx/nginx.conf"
      - "{{ nup_containers_data_dir }}/{{ nup_container_name }}/vhosts:/etc/nginx/vhosts"
    restart_policy: always
    restart: "{{ 'yes' if nup_config.changed or nup_ng_config.changed else omit }}"
  async: 600
  poll: 1
